### ISSUE TITLE
I worry `module.parent` is too magic, and not necessarily robust.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/conf#1]
https://nodejs.org/api/modules.html#modules_module_parent

> The module that first required this one.

My understanding is that means if you've got two modules:

```js
// A.js

require('conf');
````

```js
// B.js

require('conf');
```

Then `module.parent` will be whichever one got loaded first. That seems like a recipe for hard-to-debug issues.

I would just modify your constructor so you can do:

```js
Conf('my-module');
```

as a shortcut for `{projectName: 'my-module'}`

**Comment by sindresorhus** [comment]
Read the comment in the code. That's exactly why I do this: https://github.com/sindresorhus/conf/blob/d2349738648ee751ef3409c93829b92c46d610ce/index.js#L12

This trick is proven to work reliably. I've been using it for years in a [myriad of packages](https://github.com/sindresorhus/meow/blob/bf66f3adcbc3a6eb5863ad59c6c77b84944a98e8/index.js#L13-L15).

**Comment by sholladay** [comment]
I have been seeking a great solution to this problem of "get the user's package.json" and was wondering about that pattern as well.

For many modules that export a function, a sensible approach may be a combo of [read-pkg-up](https://github.com/sindresorhus/read-pkg-up) and [caller-path](https://github.com/sindresorhus/caller-path). I know at least [meow](https://github.com/sindresorhus/meow/blob/6969b818556625df855ab544650bc3ca48d62534/index.js#L25) uses the former, but not the later.

**Comment by sindresorhus** [comment]
@sholladay I sometimes use https://github.com/sindresorhus/parent-module too, but it's just easier to use this trick instead.

**Comment by jamestalmage** [comment]
Clever.

It seems to me that the comment does not accurately describe what is happening though. It should be something like:

> Prevent caching of this module, so module.parent is always accurate

It's actually deleting itself from the cache, not some previously cached instance.

**Comment by sindresorhus** [comment]
@jamestalmage Good point. Fixed.
