### ISSUE TITLE
Add the ability to unsubscribe from `onDidChange`

### ISSUE THREAD

**Issue by TheRealSyler** [sindresorhus/conf#101]
im using the `electron-store` package for a electron/react app and on `componentDidMount` im calling the  `onDidChange` method of the store the problem is im getting an error when the component is unmounted because the callback references the component, so a unsubscribe thing would be good to prevent this kind of issue.

i can help adding it, i already have some vague ideas on how this could be implemented, just want to be sure that something like this would be merged so that i don't waste my time.

**Comment by sindresorhus** [comment]
Makes sense. PR welcome :)

Should ideally be added to `onDidAnyChange` too.

**Comment by TheRealSyler** [comment]
turns out, you already can unsubscribe. 

the test below will pass.
```js
test('Remove listeners (`onDidChange/onDidChangeAny`)', t => {
	const conf = new Conf({key: 'test'});
	let test = '';
	const a = conf.onDidChange('key', e => {
		test = e;
	});
	conf.set('key', 'value');
	a();
	conf.set('key', 'another value');
	t.is(test, 'value');
});
```

in conclusion the only thing that needs to be updated is the readme.
