### ISSUE TITLE
Jest, console.warn require.cache modification is not permitted

### ISSUE THREAD

**Issue by danielweck** [sindresorhus/conf#110]
Due to this:
https://github.com/facebook/jest/pull/9841/files
and this:
https://github.com/sindresorhus/conf/blob/410cc144141f1467cc91fe4b16f6b7f42a8afac8/index.js#L21-L23
=>
```
console.warn
    `require.cache` modification is not permitted
```
(output'ed many times in the console when unit-testing, with full stacktrace, so quite disruptive, albeit non-fatal unless unit-tests check for CLI output)

**Comment by sindresorhus** [comment]
Fixed in v11: https://github.com/sindresorhus/conf/releases/tag/v11.0.0
