### ISSUE TITLE
Add a way to change default config path

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/conf#112]
I like to keep the config of some tools that use `conf` under git, and be able to easily use the backed-up configs in unix systems. The current default config path keeps changing, which doesn't lend itself to this. Ideally, I want everything stored under `~/.sindconf/`.

**Comment by sindresorhus** [comment]
What do you mean by "default config path keeps changing"? The path has never changed. On Linux, it respects `XDG_CONFIG_HOME`, so you could set that to change the config path.
