### ISSUE TITLE
reset without arguments (keys)

### ISSUE THREAD

**Issue by willium** [sindresorhus/conf#135]
Currently, calling `MyStore.reset()` without any arguments is a noop (without any warnings), contrary to what I would expect (and I imagine others). At the very least, perhaps a basic solution to just that problem:
1. Warn if no key are provided
2. Type should require at least one key, e..g `reset(key: string, ...keys: string[])`

Furthermore, my expectation was that calling reset without arguments would reset all the keys. 
E.g.
```ts
const keys = Object.keys(MyStore) as (keyof (typeof MyStore.store))[]
MyStore.reset(...keys)
```
However even this isn't correct, because it would only reset those keys in the current store value, not all keys (e.g. if there were some keys undefined, they would not be reset to their defaults).

**What I am most interested in is some method `resetAll()` that effectively resets the entire store to be equal to the originally provided value to defaults, with no additional properties.**

----
```ts
const defaults = { a: 1, b: 2 }
MyStore = new Conf({ ..., defaults }) // current value is { a: 1, b: 2 }
MyStore.store = { c: 3 } // current value is { a: 3 }
MyStore.reset() // noop <-- unexpected
MyStore.reset(...Object.keys(MyStore.store)) // current value is { }  <-- unexpected
MyStore.reset(...Object.keys(defaults)) //  current value is { c: 3} <-- unexpected
MyStore.store = defaults //  current value is { a: 1, b: 2 } which is what I would expect MyStore.reset() to do
```

**Comment by willium** [comment]
There also exists a method `clear()` but that does not reset values to the defaults as would be expected, unfortunately.

**Comment by sindresorhus** [comment]
> contrary to what I would expect (and I imagine others).

I cannot speak for others, but as a user, I would be surprised if an API worked like this. It would make it way too easy to accidentally delete all data if you for some reason forgot to pass a key, or the key was accidentally undefined. It would just not be a good API.

> Warn if no key are provided
> Type should require at least one key, e..g reset(key: string, ...keys: string[])

I disagree. This might sound nice in theory, but in practice, it makes it annoying to pass arrays of keys that may or may not be empty.

**Comment by sindresorhus** [comment]
Can you check out https://github.com/sindresorhus/conf/pull/136 ?

**Comment by willium** [comment]
Thank you for following through on this! I left a couple comments. Totally reasonable to just use clear and leave rest alone :) thanks for adding the comment
