### ISSUE TITLE
Cannot use schema validate from ajv

### ISSUE THREAD

**Issue by kamontat** [sindresorhus/conf#142]
# Problem

The generated code on schema section is below

![shot-07_02_2021-00_18_46](https://user-images.githubusercontent.com/14089557/107125100-6dd88e00-68da-11eb-9813-c7a0bbbca224.png)

```javascript
const ajv_1 = require("ajv");

if (options.schema) {
    if (typeof options.schema !== 'object') {
        throw new TypeError('The `schema` option must be an object.');
    }
    const ajv = new ajv_1.default({ // problem from here
        allErrors: true,
        useDefaults: true
    });
    const schema = {
        type: 'object',
        properties: options.schema
    };
    __classPrivateFieldSet(this, _validator, ajv.compile(schema));
    for (const [key, value] of Object.entries(options.schema)) {
        if (value === null || value === void 0 ? void 0 : value.default) {
            __classPrivateFieldGet(this, _defaultValues)[key] = value.default;
        }
    }
}
```

it add `.default` after require ajv from node_modules but when ajv export, it didn't use any default key as screenshot below

![shot-07_02_2021-00_24_52](https://user-images.githubusercontent.com/14089557/107125203-0707a480-68db-11eb-911f-e99879016956.png)

So now it throw `TypeError: ajv_1.default is not a constructor` error.

P.S I use this via `electron-store` library

## Version

**conf**: version `9.0.0`
**os**: Macos version `11.1 (20C69)` Big Sur
**node**: `v15.5.1`
**yarn**: `v1.22.10`

**Comment by sindresorhus** [comment]
I just `npm install ajv` and it doesn't have a `.default` property. You are looking at the `lib` folder, while you need to look at `dist`.

**Comment by kamontat** [comment]
![shot-07_02_2021-00_37_31](https://user-images.githubusercontent.com/14089557/107125443-aed1a200-68dc-11eb-9aa4-f7a0f841751b.png)

I should see on lib, because it specify main file to `lib/` folder
