### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by AlmirKadric** [sindresorhus/conf#15]
This is a feature request, wondering if we could have YAML support.
Will try an open a PR to add this feature, expect it won't be too much code.

**Comment by SamVerschueren** [comment]
Not sure why you want `conf` to use YAML because you barely touch the store directly. It only adds bloat imo as it requires a custom parser.

So I think it might be better if you create something like `yaml-conf` and just extend this `Conf` class and write to a YAML file instead of a JSON file.

**Comment by AlmirKadric** [comment]
thanks for the advice, will that instead then 👍

**Comment by AlmirKadric** [comment]
Woops I didn't read the last line, if its still in the decision process I'll make my case.

For my configuration system i plan to have 3 forms of configuration all intertwined, `default` application config, `appData` config and `dotfile` config. The idea was for the latter 2 to use the conf library to provide them. However for the `dotfile` using `yaml` rather than JSON would be preferable.

Also by having conf support this, I don't need to resort to the hackery you mentioned above. IMHO the idea behind conf is to make these kinds of things simple.

**Comment by sindresorhus** [comment]
Sorry, not interested in YAML support.
