### ISSUE TITLE
Proxied object

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/conf#156]
Would be nice if conf provided a proxy that allows the config to be accessed and set more easily. For example:

```js
const {store} = new Conf();

store.a = 2;
store.a++;

console.log(store.a);
//=> 3
```

We'd probably need to assign it to a different name though.

**Comment by sindresorhus** [comment]
I did consider it in the past, but I decided not to as it would hide the fact that each mutation is a fairly expensive method call.
