### ISSUE TITLE
Add a `mode` option

### ISSUE THREAD

**Issue by ncallaway** [sindresorhus/conf#157]
Add a `mode` option that will be used for writing the config file. This feature may be useful if you want to produce a config file that is not world or group readable (or writable).

An example use case is the `aws cli`, which allows the user to configure a profile with `aws configure --profile [profilename]`. The profiles are configured in `~/.aws/config` and `~/.aws/credentials` with a `0o600` mode.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/conf/pull/158
