### ISSUE TITLE
Bad performance due to slow ajv.compile called.

### ISSUE THREAD

**Issue by mrchaofan** [sindresorhus/conf#161]

**Comment by mrchaofan** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/24412720/156731287-0a3651a2-6f31-4269-8486-a27ec01bffd6.png">
ajv is really time consuming, do you have any ideas for this optimization?

**Comment by sindresorhus** [comment]
I would recommend opening an issue on the Ajv issue tracker instead. I don't think there's much Conf can do about slow Ajv performance.

**Comment by mrchaofan** [comment]
Sorry. I should have thought of raising an issue for ajv not for the conf😂. I close this issue.
