### ISSUE TITLE
Ajv is in strictmode

### ISSUE THREAD

**Issue by tganzhorn** [sindresorhus/conf#169]
Ajv is in strictmode which makes the usage of validation keywords impossible.

Solution: 
Disable strictmode for ajv.

**Comment by sindresorhus** [comment]
How does it make it impossible? Can you please elaborate a little bit more?

**Comment by tganzhorn** [comment]
Ok I have to rephrase that. We can’t use user defined keywords. Like for example when I want to use a visible keyword on an object for later usage. Ajv throws an error on unknown keywords, and since we don’t have a way to add custom keywords it’s impossible to use that feature. Ajv enabled strict mode in some release I don’t quite remember but there’s a possibility you didn’t catch that change. Greetings from Germany and sorry for my mediocre English 😅

**Comment by sindresorhus** [comment]
Ok found it: https://ajv.js.org/strict-mode.html#prohibit-ignored-keywords

**Comment by sindresorhus** [comment]
Wouldn't it be better to support adding custom keywords? Strict mode brings a lot of good. I don't think I want to disable it.

**Comment by tganzhorn** [comment]
I guess that’s also a possibility, or let the user decide if he wants to disable strict mode completely or wants to add custom keywords.

**Comment by tganzhorn** [comment]
And yeah strict mode brings a lot of good stuff but sometimes you gotta use them custom keywords 😁

**Comment by sindresorhus** [comment]
I think we could add a `schemaOptions` top-level option that accepts a `additionalKeywords` option.

**Comment by tganzhorn** [comment]
You can assign this issue to me if you want to. I‘m sure I can add this feature to the codebase.

**Comment by CalebUsadi** [comment]
I've provided a way to resolve this issue in #196. You would use the option:
```js
ajvOptions: {
    strict: false
}
```
