### ISSUE TITLE
Support for ESM

### ISSUE THREAD

**Issue by pepicrft** [sindresorhus/conf#170]
Hi, are there plans to support ESM?
We are using `conf` from an ESM-based CLI and because Conf is CJS the loading of the various modules that are part of this package can't be loaded concurrently with the rest of the modules of the CLI.

I'd be happy to go ahead with the implementation but I'd need some input on what the suggested tooling is for generating CJS and ESM modules. Thanks in advance.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/conf/releases/tag/v11.0.0

**Comment by pepicrft** [comment]
You are amazing ❤️! Thanks a lot Sindre

**Comment by pepicrft** [comment]
I noticed an [issue](https://github.com/sindresorhus/conf/pull/172) in the `package.json`. I'd appreciate a review on it.
