### ISSUE TITLE
Is conf typescript-responsive or have type declarations?

### ISSUE THREAD

**Issue by hugoovf** [sindresorhus/conf#174]
For some reason, I'm having this issue on importing this package.
![image](https://user-images.githubusercontent.com/69076992/214198288-2877ef26-aafc-43ba-adcb-1fcd8108ba2e.png)

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by hugovidafe** [comment]
Hey, nice support ^^

**Comment by mikkotikkanen** [comment]
Did you manage to sort it out? I have a pure ESM application but it's giving me the same type error. 🤔
