### ISSUE TITLE
copyright-question

### ISSUE THREAD

**Issue by ArthurLobopro** [sindresorhus/conf#180]
I decided to use your code to build a `electron-store` and `conf` packages that use `zod` instead of `ajv` for my own proposes.

I know  this repository use MIT license but I don't know how to publish other version respecting the license, can you help me with this? 

Here is some questions that I have:

* How can I refers this project as original code?
* Can I update these fields (`repository`, `author`, `funding`)  in `package.json` file?

**Comment by sindresorhus** [comment]
This is not really the place to ask license questions, but ok.

You need to include the copyright statement from the license file here in your license file.

You should also make it clear in the description how it differs from this one.

**Comment by sindresorhus** [comment]
> Can I update these fields (repository, author, funding) in package.json file?

Yes
