### ISSUE TITLE
Switch from Buffer to Uint8Array

### ISSUE THREAD

**Issue by dreamorosi** [sindresorhus/conf#188]
Hi!

I have read your [Goodbye, Node.js Buffer](https://sindresorhus.com/blog/goodbye-nodejs-buffer) post where you mentioned that you'd be open to contributions to move your packages to use `Uint8Array`.

I'd like to volunteer to do so for this package.

I have already [a fork with the changes & tests passing](https://github.com/sindresorhus/conf/compare/main...dreamorosi:conf:feat/swap_buffer_with_uint8array), I have used your [uint8array-extras](https://github.com/sindresorhus/uint8array-extras) package. 

Let me know if a PR would be welcome, if not or have different plans no worries!

**Comment by sindresorhus** [comment]
Definitely. Pull request most welcome 🙏
