### ISSUE TITLE
Build not passing - silent fail? 

### ISSUE THREAD

**Issue by kasperlewau** [sindresorhus/conf#2]
I hate to be this guy *(chill, it's 0.10.0...)* but, you've got an [.only](https://github.com/sindresorhus/conf/blob/master/test.js#L144) that's reporting a non-passing build as passing on Node@5.11.1 & Node@6.2.0 with a clean `npm i`. 

![failing](https://i.imgur.com/4mzDLK4.png)

Builds on 
* Travis (https://travis-ci.org/sindresorhus/conf/jobs/139352324#L653)
* AppVeyor (https://ci.appveyor.com/project/sindresorhus/conf/build/6/job/ccvy2qihrr40tqh8#L770)

--- 

I'd submit a PR, but my head is not where it's supposed to be right now and duty calls (*laundry...*). Just though I'd let you know. Cheers! 🔨

**Comment by sindresorhus** [comment]
Ugh. Thanks for reporting :) Luckily, I only had a couple of incorrect tests. Code was working perfectly.

`.only` is so dangerous! I actually have XO, which bundles the https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-only-test.md rule, which should have caught this. @jfmengels Any idea why it didn't?

**Comment by jfmengels** [comment]
Hmm, no, sounds really odd. I'll try to look into it later, but it is odd indeed.

**Comment by jfmengels** [comment]
`import {serial as test} from 'ava';` it's this part that we don't recognize. Do we want to handle this case or does that seem like a weird use of AVA? IMO, it kind of does :D, but we should probably try to handle it.

Didn't know you could destructure things like `serial` and that it was the same thing as `test.serial`. We actually don't even handle anything when AVA is not imported as `test`. Plenty of room for improvement here.

**Comment by sindresorhus** [comment]
@jfmengels I opened an issue: https://github.com/avajs/eslint-plugin-ava/issues/121
