### ISSUE TITLE
Prevent unsupported JSON values

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/conf#24]
For example, `undefined` is not supported in JSON. We should throw rather than silently coercing it.

**Comment by acheronfail** [comment]
Unsupported values include:

- the value `undefined`
    - `JSON.stringify({ foo: undefined }) ` = `"{}"`
- any `Function`
    - `JSON.stringify({ foo: function () {} })` = `"{}"`
- any `Symbol` (as a key or value)
    - `JSON.stringify({ foo: Symbol('foo') })` = `"{}"`
    - `JSON.stringify({ [Symbol('foo')]: 'foo' })` = `"{}"`


Also, non-enumerable properties aren't supported (from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)).
```js
const value = Object.create(null, {
  x: {
    value: 'x',
    enumerable: false
  },
  y: {
    value: 'y',
    enumerable: true
  }
});

JSON.stringify(value); // '{"y":"y"}'
```

**Comment by acheronfail** [comment]
I think checking for the first three cases makes sense (check for `undefined`, `typeof x === 'function'` and `typeof x === 'symbol'`. That shouldn't be a difficult change.

Not sure how feasible it really is to check if every value is `enumerable` though, what do you think?

**Comment by sindresorhus** [comment]
> I think checking for the first three cases makes sense (check for undefined, typeof x === 'function' and typeof x === 'symbol'. That shouldn't be a difficult change.

👍 

> Not sure how feasible it really is to check if every value is enumerable though, what do you think?

Yes, doesn't make sense to check for this.
