### ISSUE TITLE
Asynchronousity?

### ISSUE THREAD

**Issue by ccnokes** [sindresorhus/conf#3]
The setter for store (https://github.com/sindresorhus/conf/blob/master/index.js#L82) is synchronous which is probably a good thing, but in some scenarios where I may be doing a lot of setting, I'd like it to be async. If I were to PR this with a `setAsync` method, is that something that you'd consider? 

Thanks for the handy package btw 😸 .

**Comment by sindresorhus** [comment]
In what scenarios would it be beneficial for it to be async? Note that you can set many properties in one call. Also keep in mind that async comes with overhead and usually it's a lot faster to do it sync when blocking the event loop is not a problem (pretty much everything other than servers).

**Comment by ccnokes** [comment]
I changed my mind 😸 , and you make a good point. I also realized that in the context of an Electron app (my use case), if you quit the app while an async write is pending, the data never gets written to the file and all the data in the existing file (if there is one) is lost.

**Comment by brian-mann** [comment]
Here is one use case - `graceful-fs`. We are dealing with a situation where *every* fs read/write call needs to be async so it goes through `graceful-fs`. Without that, EMFILE errors bubble up.

**Comment by magicdawn** [comment]
https://www.electronjs.org/docs/tutorial/performance#3-blocking-the-main-process

> 3) Avoid using blocking I/O operations in the main process. In short, whenever core Node.js modules (like fs or child_process) offer a synchronous or an asynchronous version, you should prefer the asynchronous and non-blocking variant.
