### ISSUE TITLE
concurrency in ava

### ISSUE THREAD

**Issue by djalmaaraujo** [sindresorhus/conf#31]
Do you recommend using `.serial` for tests using this module? Any suggestion for a library that uses `conf` module? It fails since they use the same storage (this module), so I needed to add `.serial` to those tests.

**Comment by SamVerschueren** [comment]
Support questions are better asked on StackOverflow.

To give you a quick answer. Yes it is possible, but it really depends on how you are using `Conf`. If you look at the tests of `Conf` itself, if you are able to pass in `cwd` from within your tests, you can run them concurrently. If not, you will have to run them serially.

**Comment by djalmaaraujo** [comment]
@SamVerschueren thanks, your answer is enough for me. I appreciate your fast response.
