### ISSUE TITLE
Problematic file write upon instantiation

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/conf#32]
I have a bitbar plugin that gets refreshed every second, 99% of the times it just reads data from the configuration without mutating it in any way.

In `conf`'s constructor there's this line:
```
this.store = Object.assign(obj(), opts.defaults, this.store);
```

Which calls `store`'s setter method, which writes back to disk the value of the store we just read. Basically every instantiation causes a write, this may be problematic in some use cases.

This is a problem for me because I have the actual `json` file stored in the dropbox folder, and being it constantly re-written every second it causes Dropbox to consume 20% of my CPU just for syncing this one file that actually almost never changes.

Is this behavior intentional? If so, would you consider a PR adding an option for disabling it?

**Comment by sindresorhus** [comment]
It's just an oversight. PR welcome to fix it :)
