### ISSUE TITLE
Make the -nodejs suffix configurable

### ISSUE THREAD

**Issue by MegaGM** [sindresorhus/conf#35]
Related: https://github.com/sindresorhus/env-paths/issues/2

**Comment by sindresorhus** [comment]
Why do you need this? What's your use-case?

**Comment by MegaGM** [comment]
1. To store a `database.json` file within `app.getPath('userData')` directory (with no `-nodejs` suffix)
2. To use the same `database.json` file in different processes. Electron's `main` and `renderer`, as well as non-Electron app.

**Comment by sindresorhus** [comment]
Alright, PR welcome :)
