### ISSUE TITLE
Invalid version in npm registry

### ISSUE THREAD

**Issue by bampakoa** [sindresorhus/conf#60]
@sindresorhus I think that the version of the library in the npm registry is not correct. The registry reads version **2.2.0** but `index.js `does not have changes from this release

**Comment by sindresorhus** [comment]
Can you be more exact on what's missing/wrong?

**Comment by bampakoa** [comment]
Ok, it was not clear for me whether the last commits were in the 2.2.0 version. As I can see, 2.2.0 is behind the `master` branch. Sorry about the fuss. Are you going to release them any time soon?
