### ISSUE TITLE
Add store migrations

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/conf#74]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/conf/issues/74)

See https://github.com/sindresorhus/conf/pull/49 for an initial attempt that went stale. Please take into account all the feedback given there if you intend to take on the issue.

Part of this task is also to bring the docs over to `electron-store` to resolve https://github.com/sindresorhus/electron-store/issues/19.

---

> Note: This is not an easy issue. It requires you to have good JavaScript and Node.js experience. I expect you to do a good job. Instead of asking to many questions, present solutions. The point of a issue bounty is to give me less work, not more. 🙌

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#83 Adds support for migrations](https://issuehunt.io/r/sindresorhus/conf/pull/83)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/conf/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by rafaelramalho19** [comment]
I'm more than happy to pick this up.

Wish me luck 🤞
