### ISSUE TITLE
`.set(object)` detection might be wrong

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/conf#8]
Currently, this is the implementation of `.set(key, val)` which supports `.set(object)` as well.

```js
set(key, val) {
	const store = this.store;

	if (val === undefined) {
		Object.keys(key).forEach(k => {
			dotProp.set(store, k, key[k]);
		});
	} else {
		dotProp.set(store, key, val);
	}

	this.store = store;
}
```

If someone calls `set('foo')` or `set('foo', undefined)`, `Object.keys('foo')` returns `[0, 1, 2]` and the store will look like this 

```
{
    '0': 'f', 
    '1': 'o', 
    '2': 'o'
}
```

I believe we should add extra checks to the `set` method. But the first question to answer is, is `string` the only valid input type for `key`?

1. Test that `key` is of type `string` or `object`.
2. Test if `key` is of type `object` AND `value` is `undefined`.
  - We could ignore `value` in this case
  - We could throw an error indicating that it's not possible to provide a `value` if `key` is of type `object`

**Comment by sindresorhus** [comment]
> is string the only valid input type for key?

Yes.

-

Extra checks sounds good.
