### ISSUE TITLE
Constructor fails when `/tmp` directory is not writable

### ISSUE THREAD

**Issue by Timer** [sindresorhus/conf#93]
```js
{ Error: EACCES: permission denied, open '/tmp/.config/nextjs-nodejs/config.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Conf.get store [as store] (/var/app/current/node_modules/conf/index.js:228:18)
    at new Conf (/var/app/current/node_modules/conf/index.js:92:26)
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/tmp/.config/nextjs-nodejs/config.json' }
```

I'm not sure if this would be better raised in `env-paths` for giving an unwritable path.

However, I think this error would be better deferred until trying to use the `Conf` instance (e.g. get/set).

x-ref: https://github.com/zeit/next.js/issues/9294

**Comment by sindresorhus** [comment]
I’m not sure how deferring it will help? You’ll eventually get a write error anyway. Also, if the `defaults` option is used, it needs to write the defaults right away.

**Comment by Timer** [comment]
It was just an idea! I feel like a constructor throwing for an access error is unexpected, whereas code will likely handle failure scenarios in the `get`/`set`s.

I'll close this and add a `try { } catch { }` around `new Conf(...)`. Thanks for responding!
