### ISSUE TITLE
configName not working

### ISSUE THREAD

**Issue by philippkuehn** [sindresorhus/conf#97]
```js
new Conf({
  configName: 'foo',
})
```

still creates a `config.json` instead of `foo.json`.

**Comment by sindresorhus** [comment]
We actually have a test that proves that this works: https://github.com/sindresorhus/conf/blob/514469ad4cdf42658492cee5e3d0b4eadbf3de33/test.js#L186-L197

**Comment by philippkuehn** [comment]
I tried it again and it actually works. Probably I had made a mistake then. Sorry!
